### ISSUE TITLE
Faulty log message when playing as non-red player

### ISSUE THREAD

**Issue by Loobinex** [Loobinex/keeperfx-unofficial#36]
When you play a level as something else as player0, you'll get an message in the log file that says:

> No model defined for Player #, assigned computer model #

This was something left in when implementing 5c90d480456671d7463d720fd533a68fba8b9a58, but deemed to be inconsequential. However, since implementing the feature to play campaigns with different players(a49f03b0bc98ac1dad859991c0dc93d0e04838a8) it will occur more frequently.

To reproduce, simply launch the game with command line parameters '-level 5 -human 1', close the game again and open the log file.

**Comment by OrsonMaxwell** [comment]
Ok I tracked this down to the player_exists() function that does not consider player 0 at all. Then the player->field_2C field seems to tell the engine that there should not be a computer AI controlling the player while the whole thing fails because player0 never gets the PlaF_Allocated bit in the player->allocflags field set. Digging further...

**Comment by Loobinex** [comment]
There's not much to track down. This is not a bug you introduced, this is something we introduced knowingly a few versions back. We just felt that nobody uses the '-human' parameter anyway so it did not matter. With your change the issue has become a bit more prominent. (but still not that important, it's just a log message you can ignore).

There's no need for you to investigate, spartahawk knows exactly what's the cause.
